site_name: VBGS-SLAM — Math Derivations
site_description: Full mathematical derivations for VBGS-SLAM
site_url: https://Yuhanelle.github.io/vbgs-derive
repo_url: https://github.com/Yuhanelle/vbgs-derive
repo_name: vbgs-derive

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - content.code.copy
    - content.action.edit       # shows “Edit this page” linking to *this repo*
    - toc.integrate
    - header.autohide
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Derivations:
    - Generative model: derivations/generative-model.md
    - Variational inference (ELBO): derivations/variational-inference.md
    - E/M-step & pose update: derivations/e-m-step.md
    - Mixture updates & pruning: derivations/mixture-updates.md
    - Pose optimization & Jacobians: derivations/pose-optim.md
  - References: references.md
  - Code (vbgs-slam): https://github.com/Yuhanelle/vbgs-slam

plugins:
  - search
  - bibtex:
      bib_file: docs/references.bib
      cite_inline: true
  - mkdocs-jupyter:
      execute: false
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_signature: true
            show_source: false
            heading_level: 2

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax-config.js
